### ISSUE TITLE
QUICKSHEET: pSConfig from bare metal to MaDDash

### ISSUE THREAD

**Issue by schevali** [perfsonar/docs#152]
[https://app.zenhub.com/files/32192670/15598b58-17c7-4e39-970f-cca628677e7d/download](https://app.zenhub.com/files/32192670/15598b58-17c7-4e39-970f-cca628677e7d/download)

Making the above notes pretty for Web and PDF distribution.

**Comment by tonin** [comment]
Small improvement for the part about adding IP address to the esmond ACL: we now have a script doing all the dirty python config.  Instead of the 3 lines of code you have (starting with `cd /usr/lib/esmond`) you can just run the following command:
```
esmond_manage add_user_ip_address USERNAMEHERE IPADDRESSES/RANGESHERE
```
and you don't need to do anything to exit the esmond/python env mode.

**Comment by tonin** [comment]
And this works for authentication by key too. All is documented at http://docs.perfsonar.net/multi_ma_install.html#authenticating-measurement-hosts

**Comment by szymontrocha** [comment]
Maddash/esmond have gone away with the latest release so closing
