### ISSUE TITLE
Add troubleshooting guide

### ISSUE THREAD

**Issue by schevali** [perfsonar/docs#42]
This a placeholder issue to collect any items for addition to a Troubleshooting document for all things installation, meshconfig, and MaDDash

Example:
- check /etc/perfsonar/meshconfig-agent-tasks.conf for erroneous MA definitions and remove to cut down on log trash and processor use.

**Comment by bltierney** [comment]
started this page. See:
http://docs.perfsonar.net/release_candidates/4.0rc2/troubleshooting_overview.html

**Comment by bltierney** [comment]
all should review this, and add anything they think is missing.

**Comment by szymontrocha** [comment]
The steps are fine to me. What I would maybe add is a sentence or two for each step describing to which problem they may be applied. For instance for (2) write "If you are unable to open perfSONAR Toolkit Web interface make sure if selinux is disabled. In order to dissable..." Then it would be a bit helpful I think. For the last sentence it would be good to add how to get the archive URL first before data retrieving.
