### ISSUE TITLE
move all of https://www.perfsonar.net/deploy/ to docs.perfsonar.net

### ISSUE THREAD

**Issue by bltierney** [perfsonar/docs#59]
except https://www.perfsonar.net/deploy/network-metrics/, which can be moved up under 'about'

**Comment by bltierney** [comment]
mostly done. Leaving 'Deployment' examples for now.

**Comment by bltierney** [comment]
I think this is done, but needs review from others.

**Comment by szymontrocha** [comment]
Network metrics are now in http://www.perfsonar.net/network-metrics/
http://www.perfsonar.net/deploy/ now contains "Node placement" and "Monitoring architectural examples"
I fixed a few small things. Looks good now

**Comment by mattzekauskas** [comment]
I'm working on redirecting the former security-considerations section to docs.perfsonar.net, instead of just deleting.   I think it's possible, but don't have the permissions to access the redirect function.  If it is not possible (because it's off-site), I'll change security-considerations to be a simple statement with a link to http://docs.perfsonar.net/manage_security.html .   NOTE: if we do this, we lose the firewall port data for 3.5.1 (and former); don't know if docs.perfsonar.net should be updated for the old release to at least include the firewall data.

Right now, I have restored the former security-considerations page, since there are external links to it.

**Comment by mattzekauskas** [comment]
http://www.perfsonar.net/security-considerations/ now redirects to http://docs.perfsonar.net/manage_security.html .   Until the latter page is updated with 4.0 information it contains a circular link back to security-considerations to get iptables detail.
